### ISSUE TITLE
早报获取失败 超过重试次数

### ISSUE THREAD

**Issue by mctds** [goldfishh/chatgpt-tool-hub#14]
[INFO][2023-04-12 10:26:34][base.py:109] - 执行Tool: news中...
[INFO][2023-04-12 10:26:34][bot.py:87] - 行动输入: 给我今天的早报
[ERROR][2023-04-12 10:26:39][victorinox.py:86] - [APP] catch a Exception: Invalid URL 'Sorry, the API documentation is missing. Without the API documentation, I cannot generate the full API URL to answer the user question. Please provide the API documentation.': No scheme supplied. Perhaps you meant https://Sorry, the API documentation is missing. Without the API documentation, I cannot generate the full API URL to answer the user question. Please provide the API documentation.?
[INFO][2023-04-12 10:26:43][base.py:109] - 执行Tool: news中...
[INFO][2023-04-12 10:26:43][bot.py:87] - 行动输入: 给我今天的早报
[ERROR][2023-04-12 10:26:47][victorinox.py:86] - [APP] catch a Exception: Invalid URL 'Sorry, the API documentation is missing. Please provide the necessary information to generate the API url.': No scheme supplied. Perhaps you meant https://Sorry, the API documentation is missing. Please provide the necessary information to generate the API url.?
[ERROR][2023-04-12 10:26:47][victorinox.py:90] - exceed retry_num
[ERROR][2023-04-12 10:26:47][tool.py:92] - 超过重试次数
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 84, in ask
    return self.bot.run(query)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 156, in _call
    next_step_output = self._take_next_step(
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 122, in _take_next_step
    observation = tool.run(
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/base_tool.py", line 73, in run
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/base_tool.py", line 70, in run
    observation = self._run(tool_input)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/news/news.py", line 41, in _run
    return self.api_chain.run(query)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/api/base.py", line 73, in _call
    api_response = self.requests_wrapper.get(api_url)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/web_requests/wrapper.py", line 93, in get
    response = requests.get(url, headers=self.headers, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'Sorry, the API documentation is missing. Without the API documentation, I cannot generate the full API URL to answer the user question. Please provide the API documentation.': No scheme supplied. Perhaps you meant https://Sorry, the API documentation is missing. Without the API documentation, I cannot generate the full API URL to answer the user question. Please provide the API documentation.?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 84, in ask
    return self.bot.run(query)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 156, in _call
    next_step_output = self._take_next_step(
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 122, in _take_next_step
    observation = tool.run(
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/base_tool.py", line 73, in run
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/base_tool.py", line 70, in run
    observation = self._run(tool_input)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/news/news.py", line 41, in _run
    return self.api_chain.run(query)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/chains/api/base.py", line 73, in _call
    api_response = self.requests_wrapper.get(api_url)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/tools/web_requests/wrapper.py", line 93, in get
    response = requests.get(url, headers=self.headers, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'Sorry, the API documentation is missing. Please provide the necessary information to generate the API url.': No scheme supplied. Perhaps you meant https://Sorry, the API documentation is missing. Please provide the necessary information to generate the API url.?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt-on-wechat-1.2.1.2/plugins/tool/tool.py", line 88, in on_handle_context
    _reply = self.app.ask(query, user_session)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 88, in ask
    return self.ask(query, chat_history, retry_num + 1)
  File "/usr/local/lib/python3.10/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 91, in ask
    raise TimeoutError("超过重试次数")
TimeoutError: 超过重试次数
[ERROR][2023-04-12 10:26:47][tool.py:93] - 超过重试次数
[INFO][2023-04-12 10:26:47][chat_gpt_bot.py:36] - [CHATGPT] query=请你随机用一种聊天风格，提醒用户：这个问题tool插件暂时无法处理
[INFO][2023-04-12 10:27:05][wechat_channel.py:174] - [WX] sendMsg=Reply(type=TEXT, content=[GPT] 嘿，你好啊！非常抱歉，我需要告诉你一件事。这个问题需要使用特定的工具插件来处理，而目前我的系统暂时没有这些插件。因此，我不能为您提供解决方案。但是别担心，我一直在快速学习和发展，希望不久的将来，我可以回答所有您的问题。非常感谢您的理解！), receiver=@45c666477c9b891bdfc3396a9547cf48cabd79e5d17e5650a31b03a69c980484

**Comment by Maddaxman** [comment]
+1 早报和天气都不稳定，早报没试过成功，我看控制台，早报没有调用morning new的tool，调用的是url的那个

**Comment by goldfishh** [comment]
pr

> +1 早报和天气都不稳定，早报没试过成功，我看控制台，早报没有调用morning new的tool，调用的是url的那个 已经升级到0.3.9

我还没向那边提pr，所以新tool用不了

**Comment by goldfishh** [comment]
感谢author提出的这个问题，这个问题发生在你request_timeout设置过短第一次访问不成功需要重试时会发生，解决思路是增大request_timeout 并且 设置 早报tool新出的可选参数morning_news_use_llm 为false（我已设置成默认，只是想让你知道有这个参数）
ChatGPT回复：Sorry, the API documentation is missing.  的bug我已经在4.23号修复，可使用0.4.2版本

**Comment by goldfishh** [comment]
> 天气预报也是这样，但是纬度上海可以？ ![20230412103933](https://user-images.githubusercontent.com/77908808/231333894-c244fa93-e3e8-4c0c-b292-a04a03b08bf7.jpg)
> 
> [INFO][2023-04-12 10:41:31][base.py:109] - 执行Tool: the action to take, should be one of [python, terminal, meteo-weather, bing-search, news, url-get]中... [INFO][2023-04-12 10:41:31][bot.py:87] - 行动输入: meteo-weather 杭州今天的天气预报 daily [INFO][2023-04-12 10:41:40][base.py:109] - 执行Tool: the action to take, should be one of [python, terminal, meteo-weather, bing-search, news, url-get]中... [INFO][2023-04-12 10:41:40][bot.py:87] - 行动输入: meteo-weather 杭州今天的天气预报 daily [INFO][2023-04-12 10:41:50][base.py:109] - 执行Tool: the action to take, should be one of [python, terminal, meteo-weather, bing-search, news, url-get]中... [INFO][2023-04-12 10:41:50][bot.py:87] - 行动输入: meteo-weather 杭州今天的天气预报 daily [INFO][2023-04-12 10:42:06][wechat_channel.py:174] - [WX] sendMsg=Reply(type=TEXT, content=[GPT] 您好！根据您之前的提问，我了解到您想了解杭州今天的天气预报。很抱歉，我无法直接获取实时天气，但是您可以查询天气预报网站或应用程序来获取最新的天气信息。感谢您的提问！), receiver=@45c666477c9b891bdfc3396a9547cf48cabd79e5d17e5650a31b03a69c980484

试一试新版本有没有这个问题，我最近有在不断更新tool 

如有问题，请重启issue
