### ISSUE TITLE
回复时间过长，经常出现HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)

### ISSUE THREAD

**Issue by 6vision** [goldfishh/chatgpt-tool-hub#6]
目前带有提示性使用tool，基本可以按照要求执行选择相应工具，但是经常链接api.openai.com超时，是由于请求超过频率了么。或者哪里使用不恰当，怎么使反应速度更快一点，亚马逊的机器和azure的机器都是这样！
日志记录如下：

[INFO][2023-04-08 01:58:36][SubscribeAccount.py:31] - [wechatmp] 162.62.81.123:36052 Receive post query ouhFW0hoT8cQC6k7HB9c3pJwNnSc 24064974339600504: $tool bing 查一下阿里公司的大模型
[INFO][2023-04-08 01:58:41][SubscribeAccount.py:31] - [wechatmp] 162.62.80.8:28940 Receive post query ouhFW0hoT8cQC6k7HB9c3pJwNnSc 24064974339600504: $tool bing 查一下阿里公司的大模型
[INFO][2023-04-08 01:58:46][SubscribeAccount.py:31] - [wechatmp] 162.62.80.57:50878 Receive post query ouhFW0hoT8cQC6k7HB9c3pJwNnSc 24064974339600504: $tool bing 查一下阿里公司的大模型
[WARNING][2023-04-08 01:58:48][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
[INFO][2023-04-08 01:58:50][SubscribeAccount.py:129] - [wechatmp] Three queries has finished For ouhFW0hoT8cQC6k7HB9c3pJwNnSc: 24064974339600504
[INFO][2023-04-08 01:58:56][base.py:99] - 执行Tool: Bing Search中...
[INFO][2023-04-08 01:58:56][bot.py:85] - 行动输入: 阿里公司大模型
[WARNING][2023-04-08 01:59:09][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
[WARNING][2023-04-08 01:59:25][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
[ERROR][2023-04-08 01:59:41][victorinox.py:87] - [APP] catch a Exception: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)
[INFO][2023-04-08 01:59:45][base.py:99] - 执行Tool: Bing Search中...
[INFO][2023-04-08 01:59:45][bot.py:85] - 行动输入: 阿里公司大模型
[WARNING][2023-04-08 01:59:57][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
[WARNING][2023-04-08 02:00:13][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12).
[ERROR][2023-04-08 02:00:29][victorinox.py:87] - [APP] catch a Exception: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)
[ERROR][2023-04-08 02:00:29][victorinox.py:91] - exceed retry_num
[ERROR][2023-04-08 02:00:29][tool.py:92] - 超过重试次数
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 85, in ask
    return self.bot.run(query)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/base.py", line 212, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 155, in _call
    next_step_output = self._take_next_step(
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/bots/bot_executor.py", line 108, in _take_next_step
    output = self.bot.plan(intermediate_steps, **inputs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/bots/bot.py", line 115, in plan
    action = self._get_next_action(full_inputs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/bots/bot.py", line 83, in _get_next_action
    full_output = self.llm_chain.predict(**full_inputs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/base.py", line 115, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/base.py", line 112, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/base.py", line 78, in generate_prompt
    raise e
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/base.py", line 75, in generate_prompt
    output = self.generate(prompt_messages, stop=stop)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/base.py", line 52, in generate
    results = [self._generate(m, stop=stop) for m in messages]
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/base.py", line 52, in <listcomp>
    results = [self._generate(m, stop=stop) for m in messages]
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/chatgpt.py", line 272, in _generate
    response = self.completion_with_retry(messages=message_dicts, **params)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/chatgpt.py", line 234, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.8/dist-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.8/dist-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/models/chatgpt/chatgpt.py", line 232, in _completion_with_retry
    return self.client.create(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py", line 527, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wechat_mp/plugins/tool/tool.py", line 88, in on_handle_context
    _reply = self.app.ask(query, user_session)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 89, in ask
    return self.ask(query, chat_history, retry_num + 1)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_tool_hub/apps/victorinox.py", line 92, in ask
    raise TimeoutError("超过重试次数")
TimeoutError: 超过重试次数
[ERROR][2023-04-08 02:00:29][tool.py:93] - 超过重试次数
[INFO][2023-04-08 02:00:29][chat_gpt_bot.py:36] - [CHATGPT] query=请你随机用一种聊天风格，提醒用户：这个问题tool插件暂时无法处理

**Comment by mctds** [comment]
我也遇到了，开始以为是更新了chatgpt-on-wechat的问题，仔细看确实是插件的问题。

**Comment by goldfishh** [comment]
> 我也遇到了，开始以为是更新了chatgpt-on-wechat的问题，仔细看确实是插件的问题。

你好，是插件配置的问题，我将更新在0.3.7版本

**Comment by goldfishh** [comment]
请在plugins/tool/config.json里的kwargs增大request_timeout 来避免这个问题，目前未设置状态下的默认值为120秒。
