### ISSUE TITLE
arxiv等插件出现问题

### ISSUE THREAD

**Issue by Abyss-Seeker** [goldfishh/chatgpt-tool-hub#63]
##### 1. 网络能够访问openai接口
是
##### 2. `git pull` 拉取最新代码
是
##### 3. 执行`pip install -r requirements.txt`，检查依赖是否满足
是
##### 4. 在已有 issue 中未搜索到类似问题
是

### 问题描述
是通过chatgpt-on-wechat 调用 $tools 的
在使用arxiv模块的时候返回报错,如下

`[INFO][2023-06-10 22:43:15][victorinox.py:111] - 提问: 请帮我查找一篇关于神经网络的论文
[INFO][2023-06-10 22:43:21][base.py:227] - LLM-OS的内心独白: 
推理：用户需要查找一篇关于神经网络的论文，可以使用arxiv工具来搜索相关论文。

[INFO][2023-06-10 22:43:21][base.py:177] - 执行Tool: arxiv中...
[INFO][2023-06-10 22:43:21][base.py:115] - 输入: 神经网络
[INFO][2023-06-10 22:43:21][tool_engine.py:134] - 我将给工具发送如下信息: 
神经网络
[INFO][2023-06-10 22:43:24][tool.py:53] - [arxiv]: search_query: {
    "search_query": "ti:neural+network",
    "max_results": 10,
    "sort_by": "relevance",
    "sort_order": "descending"
}
[INFO][2023-06-10 22:44:00][chatgpt.py:183] - proxy no find, directly request to chatgpt instead
[WARNING][2023-06-10 22:44:21][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.acompletion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
[WARNING][2023-06-10 22:44:21][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.acompletion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
[ERROR][2023-06-10 22:44:57][victorinox.py:114] - [APP] catch a Exception: Error communicating with OpenAI
[INFO][2023-06-10 22:44:57][victorinox.py:111] - 提问: 请帮我查找一篇关于神经网络的论文
[INFO][2023-06-10 22:45:02][base.py:227] - LLM-OS的内心独白: 
推理：用户需要查找一篇关于神经网络的论文，可以使用arxiv工具来搜索相关论文。

[INFO][2023-06-10 22:45:02][base.py:177] - 执行Tool: arxiv中...
[INFO][2023-06-10 22:45:02][base.py:115] - 输入: 神经网络
[INFO][2023-06-10 22:45:02][tool_engine.py:134] - 我将给工具发送如下信息: 
神经网络
[INFO][2023-06-10 22:45:04][tool.py:53] - [arxiv]: search_query: {
    "search_query": "ti:neural+network",
    "max_results": 10,
    "sort_by": "relevance",
    "sort_order": "descending"
}
[INFO][2023-06-10 22:45:40][chatgpt.py:183] - proxy no find, directly request to chatgpt instead
[WARNING][2023-06-10 22:46:01][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.acompletion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
[WARNING][2023-06-10 22:46:01][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.acompletion_with_retry.<locals>._completion_with_retry in 15.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
[ERROR][2023-06-10 22:46:37][victorinox.py:114] - [APP] catch a Exception: Error communicating with OpenAI
[ERROR][2023-06-10 22:46:37][victorinox.py:117] - exceed retry_num
[ERROR][2023-06-10 22:46:37][tool.py:108] - 超过重试次数
Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [信号灯超时时间已到]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\apps\victorinox.py", line 112, in ask
    return self.engine.run(query)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 206, in run
    return self(args[0])[self.output_keys[0]]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 112, in __call__
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 109, in __call__
    outputs = self._call(inputs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\engine\tool_engine.py", line 182, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\engine\tool_engine.py", line 140, in _take_next_step
    observation = tool.run(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 74, in run
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 71, in run
    observation = self._run(tool_input)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\arxiv_search\tool.py", line 65, in _run
    _input = SummaryTool(self.console, max_segment_length=2400).run(f"{str(file_path)}, 0")
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 74, in run
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 71, in run
    observation = self._run(tool_input)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\summary\tool.py", line 150, in _run
    map_text_list = asyncio.run(self._acall(self.map_bot, _clip_text_list))
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\summary\tool.py", line 116, in _acall
    return await asyncio.gather(*tasks)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 230, in arun
    return (await self.acall(kwargs))[self.output_keys[0]]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 150, in acall
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 144, in acall
    outputs = await self._acall(inputs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 131, in _acall
    return (await self.aapply([inputs]))[0]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 119, in aapply
    response = await self.agenerate(input_list)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 67, in agenerate
    return await self.llm.agenerate_prompt(prompts, stop)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 102, in agenerate_prompt
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 96, in agenerate_prompt
    output = await self.agenerate(prompt_messages, stop=stop)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 61, in agenerate
    results = [await self._agenerate(m, stop=stop) for m in messages]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 61, in <listcomp>
    results = [await self._agenerate(m, stop=stop) for m in messages]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 340, in _agenerate
    response = await acompletion_with_retry(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 63, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 61, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [信号灯超时时间已到]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\apps\victorinox.py", line 112, in ask
    return self.engine.run(query)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 206, in run
    return self(args[0])[self.output_keys[0]]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 112, in __call__
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 109, in __call__
    outputs = self._call(inputs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\engine\tool_engine.py", line 182, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\engine\tool_engine.py", line 140, in _take_next_step
    observation = tool.run(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 74, in run
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 71, in run
    observation = self._run(tool_input)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\arxiv_search\tool.py", line 65, in _run
    _input = SummaryTool(self.console, max_segment_length=2400).run(f"{str(file_path)}, 0")
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 74, in run
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\base_tool.py", line 71, in run
    observation = self._run(tool_input)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\summary\tool.py", line 150, in _run
    map_text_list = asyncio.run(self._acall(self.map_bot, _clip_text_list))
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\tools\summary\tool.py", line 116, in _acall
    return await asyncio.gather(*tasks)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 230, in arun
    return (await self.acall(kwargs))[self.output_keys[0]]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 150, in acall
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\base.py", line 144, in acall
    outputs = await self._acall(inputs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 131, in _acall
    return (await self.aapply([inputs]))[0]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 119, in aapply
    response = await self.agenerate(input_list)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\chains\llm.py", line 67, in agenerate
    return await self.llm.agenerate_prompt(prompts, stop)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 102, in agenerate_prompt
    raise e
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 96, in agenerate_prompt
    output = await self.agenerate(prompt_messages, stop=stop)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 61, in agenerate
    results = [await self._agenerate(m, stop=stop) for m in messages]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\base.py", line 61, in <listcomp>
    results = [await self._agenerate(m, stop=stop) for m in messages]
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 340, in _agenerate
    response = await acompletion_with_retry(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 63, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\models\chatgpt\chatgpt.py", line 61, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Codes\chatgpt-on-wechat\plugins\tool\tool.py", line 104, in on_handle_context
    _reply = self.app.ask(query, user_session)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\apps\victorinox.py", line 116, in ask
    return self.ask(query, chat_history, retry_num + 1)
  File "C:\Users\Jasper\AppData\Roaming\Python\Python39\site-packages\chatgpt_tool_hub\apps\victorinox.py", line 118, in ask
    raise TimeoutError("超过重试次数")
TimeoutError: 超过重试次数
[ERROR][2023-06-10 22:46:37][tool.py:109] - 超过重试次数
[INFO][2023-06-10 22:46:37][chat_gpt_bot.py:49] - [CHATGPT] query=请你随机用一种聊天风格，提醒用户：这个问题tool插件暂时无法处理
[INFO][2023-06-10 22:46:43][wechat_channel.py:183] - [WX] sendMsg=Reply(type=TEXT, content=你好啊！ChatGPT在这里。抱歉哦，我得提醒你一下：当前的问题咱的tool插件似乎处理不了呢。如果你有其他的问题需要解答，可以随时问我哦。是不是有什么想问的呢？), receiver=@129dabd6fb39aa350cb568ab17745f3ca229b66ac758110ed4855ddfd816f5a0
`

附加，不知道有没有帮助：config.json里面proxy我不太确定是怎么配的，用的v2RayN，发现好像在不在里面加proxy都差不多能用。。这个报错的时候在里面加了config.json的proxy值是有的，"127.0.0.1:10809"
![image](https://github.com/goldfishh/chatgpt-tool-hub/assets/112790054/b77b35f7-c929-4b66-82fd-0f5b18891aec)
同时，在使用arxiv的时候可以在v2rayN窗口底下看到如此的消息:
![image](https://github.com/goldfishh/chatgpt-tool-hub/assets/112790054/3076bb0d-be77-4c6d-a752-3ccc63be7055)
一般来说到start=9 (图中最后一个)就会断，python log里面出现[INFO][2023-06-11 00:58:52][chatgpt.py:183] - proxy no find, directly request to chatgpt instead

求解

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows
 - Python版本  ( 执行 `python -V` )：3.9                      
 - pip版本  ( 执行 `pip -V`)：21.2.4

**Comment by goldfishh** [comment]
从日志看出是网络问题，访问openai应该没有走代理，proxy在config.json配置为proxy=“http://127.0.0.1:10809”，如果你用的是wechat的tool插件**注意**是在wechat根目录下的config.json配置
如果proxy没有配置成功日志会输出：
```
proxy no find, directly request to chatgpt instead
```
如果你开的是全局代理，应该没问题（确认能不能ping通openai地址）

**Comment by Abyss-Seeker** [comment]
在deploy到railway以后自己解决了~就算报这个也能正常工作。谢谢！
